version: "3.8"

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      DATABASE_URL: "postgresql+asyncpg://eye_of_hell:pandora_24@db:5432/my_db"
    depends_on:
      - db

  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_DB: my_db
      POSTGRES_USER: eye_of_hell
      POSTGRES_PASSWORD: pandora_24
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
